replicaCount: 1

image:
  repository: jkaninda/simple-api
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  hosts: []
  annotations: {}

resources: {}

env: []
command: []
args: []

readinessProbe: {}
livenessProbe: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
