resources:
  - ../../base

configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf

generatorOptions:
  # Явно включаем хэш в имени, чтобы деплой перекатывался при изменениях:
  disableNameSuffixHash: false